### ISSUE TITLE
Mysql Connection String is broken

### ISSUE THREAD

**Issue by indigofeather** [markbates/pop#116]
try 1:
```
url: {{envOr "DATABASE_URL" "mysql://root:root@localhost:3306/database_name"}}
```
result:
```
default addr for network 'localhost:3306' unknown
```

try 2:
```
url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/database_name"}}
```
result:
```
Error 1045: Access denied for user 'mysql'@'localhost'
```

If remove the follwing code:
https://github.com/markbates/pop/commit/4800345f2750f08e50a5b9328a143b0d04fe3274#diff-fa6657a0cae6e01d3f083eed96998178
```go
if m.ConnectionDetails.URL != "" {
	return m.ConnectionDetails.URL
}
```
try 1 works fine!

Maybe the same cause as #71?

**Comment by markbates** [comment]
I'm open to a PR for this. I wouldn't recommend removing that line, but it sounds like the generated string needs to be "built correctly", whatever that means. I'm not a MySQL person.

**Comment by sio4** [comment]
Hi, @markbates and @indigofeather 

I also have same issue today and what I found is that:

* go-sql-driver/mysql uses DSN which is described on https://github.com/go-sql-driver/mysql#dsn-data-source-name 
* our URL scheme is `dialect` prefixed ("`mysql://`") and has no `(` and `)`

so I simply patch line 30 of `mysql.go` to:
```go
return strings.TrimLeft(m.ConnectionDetails.URL, "mysql://")
```
and changed my url from "`mysql://user:pass@host:port/db`" to "`mysql://user:pass@(host:port)/db`" then it works fine. (but by parser, now `m.ConnectionDetails.Host` is "`(localhost`" :-(, but anyway we don't use this value because we already have full URL. Am I right? I didn't digged deeply.


IMHO, for preserve the URL parser as is, to prevent other side effect and cunfusion for other databases, there is two choice on here.

First way is, just strings.Split(URL, "?") and get second element for preserve user's detailed settings.
Another way is, ignore mis-parsed values(host and port) and just use user specific URL in a way of DSN. 

My choice is second one since I think URL method on `yml` configuration file is for more detailed, simple and database specific configuration.

can I make a PR for this? with this solution?

**Comment by sio4** [comment]
PS.
soda configuration template also is needed to fix if we got this solution.

**Comment by markbates** [comment]
If the changes are backward compatible, then I would love a PR. I just don't want to break existing MySQL users.

**Comment by sio4** [comment]
OK, I agree.
But if we changed the URL scheme from as is to DSN compatible, (I mean just add `(` and `)`) existing user's configuration must be changed (also just add `(` and `)` :). otherwise we need to fix the parser to handle both old and DSN way.

In my opinion, existing user like me, can accept the change of URL. and I think this is more helpful for them because now they can control their own detailed configurations for DBMS connection setup!

Or... can I modify `ConnectinDetails.Finalize()` tonight (in Seoul) for parsing correctly for both?

**Comment by sio4** [comment]
Hello @markbates,
Did you checked my PR #118 for this issue? Can you give me a suggestion if it is not enough?

**Comment by markbates** [comment]
I will take a look at it this afternoon. Thanks for the reminder.

**Comment by sio4** [comment]
Oh! sorry if you feel I press you. I just wonder if I need to fix more.
Thanks!

**Comment by markbates** [comment]
No pressure. I appreciate the reminder. It's hard to keep track of everything sometimes. :)

**Comment by sio4** [comment]
Yes, I understand.
Sometimes I wonder how can you track these many codes, projects, and issues since I watched some of buffalo related projects. :-) Thank you for great job!

**Comment by indigofeather** [comment]
@sio4  Thank you
