### ISSUE TITLE
Request Simple Way to Add Additional Columns In a Join

### ISSUE THREAD

**Issue by turnkey-commerce** [markbates/pop#158]
Would like to be able to do something like the below, assuming Organizations is the parent of Users and want to see the name of the Organization with a query of users and not just the organization_id. 

```
        users := &[]struct {
		models.User
		Organization string `db:"organization"`
	}{}
        q := tx.PaginateFromParams(c.Params())
	q = q.LeftJoin("organizations", "organizations.id = users.organization_id")
        q = q.AdditionalColumns("organization.name AS organization")
        if err := q.All(users); err != nil {
		return errors.WithStack(err)
	}
```

**Comment by dougyoung** [comment]
I would like to do the same thing. I have the following resource:

```
type ClientLocation struct {
    ID        	uuid.UUID   `json:"id" db:"id"`
    CreatedAt 	time.Time   `json:"created_at" db:"created_at"`
    UpdatedAt 	time.Time   `json:"updated_at" db:"updated_at"`
    ClientID  	uuid.UUID   `json:"client_id" db:"client_id"`
    ClientName 	string
    ...
}
```

I then LeftJoin this resource with a resource that we have a foreign key to:

```go
q = q.LeftJoin("clients", "client_locations.client_id=clients.id")
sql, args := q.ToSQL(&pop.Model{Value: models.ClientLocation{}}, "client_locations.*", "clients.name as ClientName")

clientLocations := models.ClientLocations{}
if err := q.RawQuery(sql, args...).All(&clientLocations); err != nil {
    return errors.WithStack(err)
}
```

This works well. 

Having declared `ClientName` on the first resource, however, pg then complains about the field not being available during regular reads of the first resource (without the join), since `ClientName` doesn't exist in the table:

```
ERROR:pq: column client_locations.clientname does not exist
```

Naturally.

I learned that you could do the following in sqlx to ignore a database field:

```go
type ClientLocation struct {
    ID        	uuid.UUID   `json:"id" db:"id"`
    CreatedAt 	time.Time   `json:"created_at" db:"created_at"`
    UpdatedAt 	time.Time   `json:"updated_at" db:"updated_at"`
    ClientID  	uuid.UUID   `json:"client_id" db:"client_id"`
    ClientName 	string      `db:"-"`
    ...
}
```

But unfortunately this reverses the problem, causing the join to produce the message:

```
missing destination name clientname in *models.ClientLocations
```

(where `type ClientLocations []ClientLocation`) and then for straight reads of the resource to work again.

Is there a supported way of making this work?

**Comment by byungjikroh** [comment]
I was helped with @dougyoung comment above and edited to make it work temporarily.
We can use this until Issue #189 is committed. 

Use join query on the action like below. I modified @dougyoung code a bit. 
```go
q = q.LeftJoin("clients", "clients.id = client_locations.client_id")
sql, args := q.ToSQL(&pop.Model{Value: models.ClientLocation{}}, "client_locations.*", "clients.name as client_name")

clientLocations := models.ClientLocations{}
if err := q.RawQuery(sql, args...).All(&clientLocations); err != nil {
    return errors.WithStack(err)
}
```

And add joined column(clients.name as client_name) to the model with 'select'ing existed column not to make an error 'missing destination name'. (rw: "r" is optional. It means read-only field.)
```go
type ClientLocation struct {
    ID        	uuid.UUID   `json:"id" db:"id"`
    CreatedAt 	time.Time   `json:"created_at" db:"created_at"`
    UpdatedAt 	time.Time   `json:"updated_at" db:"updated_at"`
    ClientID  	uuid.UUID   `json:"client_id" db:"client_id"`
    ClientName 	string      `json:"client_name" db:"client_name" select:"clientLocation.client_id as client_id" rw:"r"` // Populated by Join
    ...
}
```

Because the error is occurred when query tries to 'select' non-existed column. 
```go
ERROR:pq: column client_locations.clientname does not exist
```

I hope this will help you. :)

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
