### ISSUE TITLE
will there be support for MongoDB?

### ISSUE THREAD

**Issue by skepticfx** [markbates/pop#173]
Buffalo framework looks amazing and it would be great to have MongoDB support in pop. Any timeline around that?

**Comment by markbates** [comment]
I would require someone who uses MongoDB to add support. Until someone steps up to add it, I don't see any timeline for it.

You can use Buffalo without Pop, just use the `--skip-pop` flag, and then you can bring your own DB to the party. The big caveat is things like the generators won't work correctly because they make the assumption of Pop.

If you want to bring MongoDB support in, it would be very, very welcome!

**Comment by skepticfx** [comment]
Thanks @markbates ! Appreciate the quick reply. Will send a pull request when I get one working :)
