### ISSUE TITLE
Compile error: vendor/github.com/markbates/pop/dialect.go:59:11: cannot assign 1 values to 2 variables

### ISSUE THREAD

**Issue by nithin-bose** [markbates/pop#197]
Created a new buffalo project with the following command:
``buffalo new ratesapp --api --with-dep --ci-provider gitlab-ci``

I get the following error when issuing ``buffalo dev``:
```
buffalo: 2018/02/01 13:40:24 === Rebuild on: :start: ===
buffalo: 2018/02/01 13:40:24 === Running: go build -v -i -o tmp/app-new-build  (PID: 65726) ===
app_new/vendor/github.com/markbates/pop
# app_new/vendor/github.com/markbates/pop
vendor/github.com/markbates/pop/dialect.go:59:11: cannot assign 1 values to 2 variables
buffalo: 2018/02/01 13:40:25 === Error! ===
buffalo: 2018/02/01 13:40:25 === exit status 2
app_new/vendor/github.com/markbates/pop
# app_new/vendor/github.com/markbates/pop
vendor/github.com/markbates/pop/dialect.go:59:11: cannot assign 1 values to 2 variables
```

**Comment by markbates** [comment]
It’s not pop, it’s the uuid library. You need to pin to their master branch. See https://github.com/satori/go.uuid/issues/66

**Comment by nithin-bose** [comment]
Shouldn't pop pin the dependency?? Like I said, all I did was run the buffalo create command and go the error on first run.

**Comment by markbates** [comment]
Pop does https://github.com/markbates/pop/blob/master/Gopkg.toml however, dep always tries to pull the latest tagged release. UUID made breaking changes, which pop was updated to work with, but they, for whatever reason, haven’t released a tag with that release yet. So dep keeps pulling in their old release. When using go get everything works fine, because master branches of both work great. It’s only when dep is involved that this is a problem. Please go to the issue I linked and complain you’ll find it’s not just pop, they broke a lot of code out there, and they’re lack of a new tag will continue to cause problems not just in pop, but any package that uses that library.

**Comment by nithin-bose** [comment]
Didn't mean to sound rude. Sorry if I did. I went and edited the file. I know, bad thing to do but since I am vendoring my dependencies, it works well.

**Comment by markbates** [comment]
I’m sorry if I sound upset, it’s not you, it’s that library. 1900 packages use it, and it’s causing problems everywhere. I wouldn’t edit any files, just set your toml file to use the master branch of uuid and everything will work. Sorry again

**Comment by nithin-bose** [comment]
No problem at all. Yea editing the toml file makes more sense. New to dep so still stumbling around ;)

Thanks! Keep up the good work!!
