### ISSUE TITLE
Default id column for models generation should be an integer

### ISSUE THREAD

**Issue by stanislas-m** [markbates/pop#33]
In terms of database optimisation, a string primary key is not efficient. The default id type for models generation, using soda, should be an integer instead of UUID.

**Comment by bigblind** [comment]
I'm not at all a database expert, but I know at least in postgres, [the performance increase over serial is limited](http://thebuild.com/blog/2015/10/08/uuid-vs-bigserial-for-primary-keys/).

I like uuid's, because id's are often used in URL's to quickly load resources. Using serial id's can cause inexperienced application developers to accidentally expose data that is meant to be private, because the id's in the url can be enumerated. Even if you implement proper authentication, serials leak information. If after signing up, I see that my user profile is at `/users/14502/`, I almost exactly how many users the site has at that moment, which is oft'en not a metric you want to have public.

I know that these are all onsiderations that developers can think of, and make their own decisions on, but the tyranny of the defaults is strong. At the cost of a tiny delay on inserts, I think avoiding information leakage by default is a good idea.

**Comment by stanislas-m** [comment]
Well, I'm more concerned about SELECT operations which use the index component of the primary key.
