### ISSUE TITLE
Mysql Connection String does not appear to work

### ISSUE THREAD

**Issue by natedsaint** [markbates/pop#71]
## ISSUE ##
In the config template, a method for connecting to a mysql via the url param is provided: (https://github.com/markbates/pop/blob/cc19c70b27a2644b315b772989ae149a4b877375/soda/cmd/generate/config_templates.go#L26). Attempting to do this results in invalid connection for different attempts.

## ATTEMPTS ##

When using something similar locally `mysql://root:root@localhost:3306/database_name` we get the following error: `default addr for network 'localhost:3306' unknown`

Same happens when using 127.0.0.1. 

Adding parens like this `mysql://root:root@(127.0.0.1:3306)/database_name` we get the following error: 
`Error 1045: Access denied for user 'mysql'@'localhost' (using password: YES)`

It seems the parsing is not working, although adding multiple debugs to connection_details.go to see the parsed path appear to show correct data, so it might be something somewhere else. Submitting as an issue while I continue to investigate in case I'm doing something wrong or there's an easy fix I'm missing.

**Comment by koesie10** [comment]
I ran into the same issue and the problem is that the MySQL driver pop is using does not use the same DSN format as pop. The DSN for the MySQL driver can be found at [go-sql-driver/mysql](https://github.com/go-sql-driver/mysql#dsn-data-source-name).

So, something like `mysql://root:root@localhost:3306/database_name` should become `root:root@tcp(localhost:3306)/database_name` for the MySQL driver. However, currently in [`mysql.go`](https://github.com/markbates/pop/blob/f47576d2cb88c7f9315d89b7d36499557d548bfa/mysql.go#L29), the raw URL is returned that was supplied to pop.

So, if that check is removed it should work.

FYI, `mysql://root:root@localhost:3306/database_name` is parsed in the MySQL driver as:

| Name  | Value |
| ------------- | ------------- |
| User  | `mysql` |
| Password  | `://root:root`  |
| Net | `localhost:3306`, should be `tcp` |
| Addr | Empty, should be `localhost:3306` |
| DB Name | `database_name` |

**Comment by markbates** [comment]
If someone has a good fix, I would a PR for this.

**Comment by koesie10** [comment]
By just removing the condition and result [here](https://github.com/markbates/pop/blob/f47576d2cb88c7f9315d89b7d36499557d548bfa/mysql.go#L29), it would be fixed. However, it does change the behaviour, so that you cannot pass a custom MySQL DSN anymore. I doubt that anyone was using that as the MySQL driver DSN is not working, so should I do a PR for this 3 line fix?

**Comment by markbates** [comment]
Yes please.
